apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gh-ingress
  # annotations:
  #   ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - backend:
            serviceName: el-github-listener-interceptor
            servicePort: 8080